/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewTypeRequirements.java
 *
 * Created on Jun 18, 2013, 3:20:51 AM
 */
package bonafide;

/**
 *
 * @author ishant0
 */
public class AddNewTypeRequirements extends javax.swing.JFrame {

    /** Creates new form AddNewTypeRequirements */
    public AddNewTypeRequirements() {
        initComponents();
        this.setTitle("Requirements"); 
        count = 0;
    }
    public AddNewTypeRequirements(AddNewTypeRequirementsClass rc) {
        initComponents();
        this.setTitle("Requirements"); 
        count = 0;
        this.rc = rc;
    }

    //Getter methods

    public String getAddress() {
        return address;
    }

    public String getCgpa_sgpa() {
        return cgpa_sgpa;
    }

    public int getCount() {
        return count;
    }

    public String getFee_structure() {
        return fee_structure;
    }

    public String getOther_requirement1() {
        return other_requirement1;
    }

    public String getOther_requirement2() {
        return other_requirement2;
    }

    public String getOther_requirement3() {
        return other_requirement3;
    }
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        panel_contain_cbs = new javax.swing.JPanel();
        cgpa_sgpa_cb = new javax.swing.JCheckBox();
        address_cb = new javax.swing.JCheckBox();
        year_cb = new javax.swing.JCheckBox();
        fee_structure_cb = new javax.swing.JCheckBox();
        back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        other_requirement1_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        other_requirement2_tf = new javax.swing.JTextField();
        other_requirement3_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose what required");

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        add_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                add_buttonKeyPressed(evt);
            }
        });

        cgpa_sgpa_cb.setText("CGPA/SGPA");

        address_cb.setText("Address");

        year_cb.setText("Admission/completion year");

        fee_structure_cb.setText("Fee structure");

        javax.swing.GroupLayout panel_contain_cbsLayout = new javax.swing.GroupLayout(panel_contain_cbs);
        panel_contain_cbs.setLayout(panel_contain_cbsLayout);
        panel_contain_cbsLayout.setHorizontalGroup(
            panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                        .addComponent(cgpa_sgpa_cb)
                        .addGap(75, 75, 75)
                        .addComponent(address_cb))
                    .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                        .addComponent(fee_structure_cb)
                        .addGap(58, 58, 58)
                        .addComponent(year_cb)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panel_contain_cbsLayout.setVerticalGroup(
            panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cgpa_sgpa_cb)
                    .addComponent(address_cb))
                .addGap(51, 51, 51)
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fee_structure_cb)
                    .addComponent(year_cb))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Require anything else:");

        jLabel3.setText("What to be changed in formate:");

        jLabel4.setText("First Requirement ");

        jLabel5.setText("Second Requirement");

        jLabel6.setText("Third Requirement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_contain_cbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(back_button)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(add_button)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(other_requirement2_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(other_requirement1_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(other_requirement3_tf, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(129, 129, 129)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panel_contain_cbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(other_requirement1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(other_requirement2_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(other_requirement3_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(back_button))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
    actionPerformed();
}//GEN-LAST:event_add_buttonActionPerformed

void actionPerformed(){
    //http://stackoverflow.com/questions/5541570/array-of-checkboxes-in-java
    //fetching values of user requirements
    if (cgpa_sgpa_cb.isSelected()){
        cgpa_sgpa = "y";
        count++;
    }
    else
        cgpa_sgpa = "n";
    if(address_cb.isSelected()){
        address = "y";
        count++;
    }
    else
        address = "n";
    if(fee_structure_cb.isSelected()){
        fee_structure = "y";
        count++;
    }
    else
        fee_structure = "n";
    if(year_cb.isSelected()){
        year = "y";
        count++;
    }
    else 
        year = "n";
    other_requirement1 =other_requirement1_tf.getText();    
    if(other_requirement1.length() != 0){
        count++;
        //System.out.println(other_requirement1+" inside antr");
    }
    else{
        other_requirement1 = "n";        
    }
    other_requirement2 =other_requirement2_tf.getText();
    if(other_requirement2.length() != 0){
        count++;      
    }
    else{
        other_requirement2 = "n";
    }
    other_requirement3 =other_requirement3_tf.getText();
    if(other_requirement3.length() != 0){
        count++;
    }
    else{
        other_requirement3 = "n";
        //System.out.println(other_requirement3+" is this???");
    }
    
    //to know total how many requirements
        if(count == 0){
             int reply = javax.swing.JOptionPane.showConfirmDialog(null, "require no items!", "Conforming", javax.swing.JOptionPane.YES_NO_OPTION);          
             if (reply == javax.swing.JOptionPane.YES_OPTION){
                this.dispose();
             }
             else{
                 new AddNewTypeRequirements(new AddNewTypeRequirementsClass()).setVisible(true);
             }
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null, "require only "+count+" items");
            rc.setCgpa_sgpa(cgpa_sgpa); 
            rc.setAddress(address); 
            rc.setCount(count); 
            rc.setFee_structure(fee_structure); 
            rc.setOther_requirement1(other_requirement1); 
            rc.setYear(year); 
            rc.setOther_requirement2(other_requirement2); 
            rc.setOther_requirement3(other_requirement3); 
    this.dispose();
}

private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    this.dispose();
}//GEN-LAST:event_back_buttonActionPerformed

private void add_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_buttonKeyPressed
    int k = evt.getKeyCode();
	if(k == java.awt.event.KeyEvent.VK_ENTER){
            actionPerformed();
	}
}//GEN-LAST:event_add_buttonKeyPressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewTypeRequirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewTypeRequirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewTypeRequirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewTypeRequirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddNewTypeRequirements().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JCheckBox address_cb;
    private javax.swing.JButton back_button;
    private javax.swing.JCheckBox cgpa_sgpa_cb;
    private javax.swing.JCheckBox fee_structure_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField other_requirement1_tf;
    private javax.swing.JTextField other_requirement2_tf;
    private javax.swing.JTextField other_requirement3_tf;
    private javax.swing.JPanel panel_contain_cbs;
    private javax.swing.JCheckBox year_cb;
    // End of variables declaration//GEN-END:variables
    private String cgpa_sgpa;
    private String address;
    private String fee_structure;
    private String year;
    private String other_requirement1;
    private String other_requirement2;
    private String other_requirement3;
    private int count = 0;
    AddNewTypeRequirementsClass rc;
    
    java.sql.Connection con;
    java.sql.PreparedStatement ps;
 
}
