/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteType.java
 *
 * Created on Jun 25, 2013, 1:31:27 AM
 */
package bonafide;


/**
 *
 * @author ishant0
 */
public class DeleteType extends javax.swing.JFrame {

    /** Creates new form DeleteType */
    public DeleteType() {
        initComponents();
        this.setTitle("Delete Certificatge Type");
        checks = new java.util.ArrayList();
        dynamicCheckboxes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Delete which type");

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        panel.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back_button)
                        .addGap(38, 38, 38)
                        .addComponent(delete_button)
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(350, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button)
                    .addComponent(delete_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    new Admin().setVisible(true); 
    this.dispose();
}//GEN-LAST:event_back_buttonActionPerformed

private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
   //getting those types which are selected to be deleted and storing them in all_selected
    java.util.ArrayList <String> all_selected= new java.util.ArrayList();
   //loop through the array of checkboxes and get the text of each checkbox that is checked
   for (javax.swing.JCheckBox ck:checks){
    if(ck.isSelected()){
        all_selected.add(ck.getText());
    }
   }
   total = all_selected.size();
   if(total == 0){javax.swing.JOptionPane.showMessageDialog(null,"select the type names you want to delete");}
   else{
       String message = "";
       if(total == 1){
           message = "Want to delete 1 type only?";
       }
       else{
           message = "Want to delete "+total+" types?";
       }
       int reply = javax.swing.JOptionPane.showConfirmDialog(null, message,"Delete certificate type", javax.swing.JOptionPane.YES_NO_OPTION);
       if(reply == javax.swing.JOptionPane.YES_OPTION){
        //deleting all selected userids from database
        for(String s : all_selected){
            try{
                Class.forName("org.sqlite.JDBC");
                //code to enable foreign key constratints on sqlite3:
                org.sqlite.SQLiteConfig config = new org.sqlite.SQLiteConfig();  
                config.enforceForeignKeys(true);                  
                con = java.sql.DriverManager.getConnection("jdbc:sqlite:./src/bonafide/bonafide.db", config.toProperties());
            //con.execute("PRAGMA foreign_keys = ON");
            ps = con.prepareStatement("delete from type where typeName = '"+s+"'");
            ps.executeUpdate();
            }catch(Exception e){javax.swing.JOptionPane.showMessageDialog(null, "Problem in deleting "+s+" from database."+e);}
            finally{
                c = new Connect();
                c.closeConnection(con, ps, null);
            }
        }
         javax.swing.JOptionPane.showMessageDialog(null, "Deleted "+total+" types from database.");
         new Admin().setVisible(true); 
         this.dispose();
   }
 }
}//GEN-LAST:event_delete_buttonActionPerformed

    
    private void dynamicCheckboxes(){
      //code for fetching existing types and adding them all to checks and generating checkBoxes :)
      try{
          c = new Connect();
        con = c.getConnection();
      
        ps = con.prepareStatement("select typeName from type");
        rs = ps.executeQuery();
        panel.setLayout(new java.awt.GridLayout(4,4,5,10));
        while(rs.next()){
                javax.swing.JCheckBox box = new javax.swing.JCheckBox(rs.getString("typeName"));  
                panel.add(box);
                checks.add(box); 
                panel.revalidate();
                panel.repaint();
                pack();            
        }
    
      }catch(Exception e){javax.swing.JOptionPane.showMessageDialog(null, "Problem in fetching all certificate types."+e);}
      finally{
          c.closeConnection(con, ps, rs);
      }
  }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeleteType().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.PreparedStatement ps;
    private java.sql.ResultSet rs;
    private Connect c;
    
    private java.util.ArrayList <javax.swing.JCheckBox> checks;
    private int total = 0;
}
