/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Requirements.java
 *
 * Created on Jun 18, 2013, 3:20:51 AM
 */
package bonafide;

/**
 *
 * @author ishant0
 */
public class Requirements extends javax.swing.JFrame {

    /** Creates new form Requirements */
    public Requirements() {
        initComponents();
    }

    public static String getAddress() {
        return address;
    }

    public static String getCgpa_sgpa() {
        return cgpa_sgpa;
    }

    public static String getFee_structure() {
        return fee_structure;
    }

    public static String getYear() {
        return year;
    }

    public static int getCount() {
        return count;
    }

    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        panel_contain_cbs = new javax.swing.JPanel();
        cgpa_sgpa_cb = new javax.swing.JCheckBox();
        address_cb = new javax.swing.JCheckBox();
        year_cb = new javax.swing.JCheckBox();
        fee_structure_cb = new javax.swing.JCheckBox();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose what required");

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        cgpa_sgpa_cb.setText("CGPA/SGPA");

        address_cb.setText("Address");

        year_cb.setText("Admission/completion year");

        fee_structure_cb.setText("Fee structure");

        javax.swing.GroupLayout panel_contain_cbsLayout = new javax.swing.GroupLayout(panel_contain_cbs);
        panel_contain_cbs.setLayout(panel_contain_cbsLayout);
        panel_contain_cbsLayout.setHorizontalGroup(
            panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                        .addComponent(cgpa_sgpa_cb)
                        .addGap(75, 75, 75)
                        .addComponent(address_cb))
                    .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                        .addComponent(fee_structure_cb)
                        .addGap(58, 58, 58)
                        .addComponent(year_cb)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panel_contain_cbsLayout.setVerticalGroup(
            panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contain_cbsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cgpa_sgpa_cb)
                    .addComponent(address_cb))
                .addGap(51, 51, 51)
                .addGroup(panel_contain_cbsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fee_structure_cb)
                    .addComponent(year_cb))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_contain_cbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(back_button)
                .addGap(51, 51, 51)
                .addComponent(add_button)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panel_contain_cbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(back_button))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
    //http://stackoverflow.com/questions/5541570/array-of-checkboxes-in-java
    //fetching values of user requirements
    if (cgpa_sgpa_cb.isSelected()){
        cgpa_sgpa = "y";
        count++;
    }
    else
        cgpa_sgpa = "n";
    if(address_cb.isSelected()){
        address = "y";
        count++;
    }
    else
        address = "n";
    if(fee_structure_cb.isSelected()){
        fee_structure = "y";
        count++;
    }
    else
        fee_structure = "n";
    if(year_cb.isSelected()){
        year = "y";
        count++;
    }
    else 
        year = "n";
    
    
    //to know total how many requirements
        if(count == 0){
             int reply = javax.swing.JOptionPane.showConfirmDialog(null, "require no items!", "Conforming", javax.swing.JOptionPane.YES_NO_OPTION);          
             if (reply == javax.swing.JOptionPane.YES_OPTION){
                this.dispose();
             }
             else{
                 new Requirements().setVisible(true);
             }
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null, "require only "+count+" items");
    this.dispose();
}//GEN-LAST:event_add_buttonActionPerformed

private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    this.dispose();
}//GEN-LAST:event_back_buttonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requirements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Requirements().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JCheckBox address_cb;
    private javax.swing.JButton back_button;
    private javax.swing.JCheckBox cgpa_sgpa_cb;
    private javax.swing.JCheckBox fee_structure_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_contain_cbs;
    private javax.swing.JCheckBox year_cb;
    // End of variables declaration//GEN-END:variables
    private static String cgpa_sgpa;
    private static String address;
    private static String fee_structure;
    private static String year;
    private static int count = 0;
    
    java.sql.Connection con;
    java.sql.PreparedStatement ps;
 
}
