/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bonafide;

import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
/**
 *
 * @author JAYESH
 */
public class Third extends javax.swing.JFrame {

    /**
     * Creates new form Third
     */
    public Third() {
        initComponents();
         try
        {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:/Documents and Settings/ishant0/bonafide.db");
    }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);             
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        create_botton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year_addmission_tf = new javax.swing.JTextField();
        year_completion_tf = new javax.swing.JTextField();
        back_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pursuing_semester = new javax.swing.JComboBox();

        jButton1.setText("jButton1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        create_botton.setText("Create");
        create_botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_bottonActionPerformed(evt);
            }
        });

        jLabel1.setText("Year of admission");

        jLabel2.setText("Year of completion");

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Pursuing semester");

        pursuing_semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pursuing_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(year_addmission_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(year_completion_tf))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(create_botton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(year_addmission_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(year_completion_tf)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pursuing_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(create_botton)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Second f1 = new Second();
      f1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

private void create_bottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_bottonActionPerformed
// TODO add your handling code here:
    try {
       /* 
       Connection conn =  DriverManager.getConnection("jdbc:sqlite:C:/Documents and Settings/ishant0/bonafide.db");
      
      JasperDesign jasperDesign = JRXmlLoader.load("E:\\PD\\pd\\pratice\\Bonafide\\src\\bonafide\\report1.jrxml");
      String name = Second.getcdt();
      //System.out.print(name);
      String sql = "select * from firstInfo order by date DESC LIMIT 1"; 
      
      
      /*java.util.Map parameters = new java.util.HashMap();
      parameters.put("name", name);
      String abc = "Hey now please work properly!!";
      parameters.put("abc", abc);
       * 
       
      
      JRDesignQuery newQuery = new JRDesignQuery();
      newQuery.setText(sql);
      jasperDesign.setQuery(newQuery);
      JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
      JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
      JasperViewer.viewReport(jasperPrint);
      
   }
   catch (Exception ex)
   {
       JOptionPane.showMessageDialog(null, ex);
   }
    */
        
       //Commented on 18-june-2013
   /*
        ps = con.prepareStatement("select * from abc"); //Table abc contains formate for certificates..............
        /* now use type table with typeName and formate datafield.....
         * 
         
        rs = ps.executeQuery();
        rs.next();
        String s = rs.getString(1);
      
            rs.close();
            ps.close(); 
        
      
        
        st = con.createStatement();
        ResultSet rs2= st.executeQuery("select * from firstInfo order by date desc limit 1");
        rs2.next();
        String name = rs2.getString("name");
        String rollnum = rs2.getString("rollnum");
        
 
        
        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(java.util.regex.Pattern.quote("name??"));
        String data[] = pattern.split(s);
        String o1 = data[0] +" "+name+" "+data[1];
             
        pattern = java.util.regex.Pattern.compile(java.util.regex.Pattern.quote("roll??"));
        data = pattern.split(o1);
        String op = data[0] +" "+rollnum+" "+data[1];
        //System.out.println(op);
        
      */
        
        
        //NWE CODE:
         //Step-1  Fetching formate from type table.
   try{
       con = Connect.getConnection();
       
       ps = con.prepareStatement("select formate from type where typeName = 'Student Bonafide'");
       rs = ps.executeQuery();
       if(rs.next()){
          formate = rs.getString("formate") ;
       }
       else{
           javax.swing.JOptionPane.showMessageDialog(null, "Internal error formate type or Certificate type not found.");
       }
       
       Connect.closeConnection(con, ps, rs); 
       System.out.println("Step 1 completed!!!");
   }catch(Exception e){
       javax.swing.JOptionPane.showMessageDialog(null, "Closing rs or ps for step 1"+e);
   }
   
   //Step-2 Fetching data which is last entered in firstInfo table.
   try{
        con = Connect.getConnection();
       
       ps = con.prepareStatement("select * from firstInfo order by date desc limit 1");
       java.sql.ResultSet rs2= ps.executeQuery();
        rs2.next();
        name= rs2.getString("name");
        rollnum = rs2.getString("rollnum");
        father_name = rs2.getString("father_name"); 
        course = rs2.getString("course");
        semester = rs2.getString("sem");
        
        
        //System.out.println(name+rollnum+father_name);
        Connect.closeConnection(con, ps, rs2);
        System.out.println("Step 2 completed!!!");
   }catch(Exception e){javax.swing.JOptionPane.showMessageDialog(null, "Problem in step 2"+e);}
   
   //Step-3 Merging data with formate
   try{
       to_deliver = Connect.splitJoin(formate, "{name}", name);
       to_deliver = Connect.splitJoin(to_deliver, "{roll}", rollnum);
       to_deliver = Connect.splitJoin(to_deliver, "(father}", father_name);
       to_deliver = Connect.splitJoin(to_deliver, "{course}", course);
       to_deliver = Connect.splitJoin(to_deliver, "{semester}", semester);
       System.out.println(to_deliver);       
       System.out.println("Step 3 completed!!!");
   }catch(Exception e){javax.swing.JOptionPane.showMessageDialog(null, "Problem while merging!"+e);}
        
        
             
        
      
        // Sending this above result op to toDeliver table:
   try{
        con = Connect.getConnection();
        ps =con.prepareStatement("insert into toDeliver (op) values(?)");
        ps.setString(1, to_deliver);
        ps.executeUpdate();
        Connect.closeConnection(con, ps, null);
   }catch(Exception e){javax.swing.JOptionPane.showMessageDialog(null, "Problem in delivering data"+e);}
        
        
        //Now code for jasper reports:
        Connection conn =  DriverManager.getConnection("jdbc:sqlite:C:/Documents and Settings/ishant0/bonafide.db");
        JasperDesign jasperDesign = JRXmlLoader.load("E:\\PD\\pd\\pratice\\Bonafide\\src\\bonafide\\report1.jrxml");
        String sql = "select * from toDeliver order by date DESC LIMIT 1"; 
      
      JRDesignQuery newQuery = new JRDesignQuery();
      newQuery.setText(sql);
      jasperDesign.setQuery(newQuery);
      JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
      JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
      JasperViewer.viewReport(jasperPrint);  
      
      //con.close();
        
    }
    catch(Exception e){
             javax.swing.JOptionPane.showMessageDialog(null, e);
    }
    
    
}//GEN-LAST:event_create_bottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Third().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton create_botton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JComboBox pursuing_semester;
    private javax.swing.JTextField year_addmission_tf;
    private javax.swing.JTextField year_completion_tf;
    // End of variables declaration//GEN-END:variables
    Connection con;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    
    private String formate;
    private String father_name;
    private String rollnum;
    private String name;
    private String course;
    private String semester;
    private String to_deliver;
}
